/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as PtoRouteImport } from './routes/pto'
import { Route as TimeEntriesRouteImport } from './routes/time-entries'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PtoRoute = PtoRouteImport.update({
  id: '/pto',
  path: '/pto',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeEntriesRoute = TimeEntriesRouteImport.update({
  id: '/time-entries',
  path: '/time-entries',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/kiosk': typeof KioskRoute
  '/payroll': typeof PayrollRoute
  '/pto': typeof PtoRoute
  '/time-entries': typeof TimeEntriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/kiosk': typeof KioskRoute
  '/payroll': typeof PayrollRoute
  '/pto': typeof PtoRoute
  '/time-entries': typeof TimeEntriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/kiosk': typeof KioskRoute
  '/payroll': typeof PayrollRoute
  '/pto': typeof PtoRoute
  '/time-entries': typeof TimeEntriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/assignments' | '/kiosk' | '/payroll' | '/pto' | '/time-entries'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assignments' | '/kiosk' | '/payroll' | '/pto' | '/time-entries'
  id:
    | '__root__'
    | '/'
    | '/assignments'
    | '/kiosk'
    | '/payroll'
    | '/pto'
    | '/time-entries'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentsRoute: typeof AssignmentsRoute
  KioskRoute: typeof KioskRoute
  PayrollRoute: typeof PayrollRoute
  PtoRoute: typeof PtoRoute
  TimeEntriesRoute: typeof TimeEntriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pto': {
      id: '/pto'
      path: '/pto'
      fullPath: '/pto'
      preLoaderRoute: typeof PtoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-entries': {
      id: '/time-entries'
      path: '/time-entries'
      fullPath: '/time-entries'
      preLoaderRoute: typeof TimeEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentsRoute: AssignmentsRoute,
  KioskRoute: KioskRoute,
  PayrollRoute: PayrollRoute,
  PtoRoute: PtoRoute,
  TimeEntriesRoute: TimeEntriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
