/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdjustmentsRouteImport } from './routes/adjustments'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as AuthenticatedOperationsRouteImport } from './routes/_authenticated/operations'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedPtoRouteImport } from './routes/_authenticated/pto'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedTimeEntriesRouteImport } from './routes/_authenticated/time-entries'
import { Route as ApiCronPurgePhotosRouteImport } from './routes/api/cron/purge-photos'
import { Route as ApiPublicKioskBootstrapRouteImport } from './routes/api/public/kiosk/bootstrap'
import { Route as ApiPublicKioskPunchRouteImport } from './routes/api/public/kiosk/punch'
import { Route as ApiPublicKioskStatusRouteImport } from './routes/api/public/kiosk/status'
import { Route as ApiPublicKioskVerifyPinRouteImport } from './routes/api/public/kiosk/verify-pin'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdjustmentsRoute = AdjustmentsRouteImport.update({
  id: '/adjustments',
  path: '/adjustments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationsRoute = AuthenticatedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPtoRoute = AuthenticatedPtoRouteImport.update({
  id: '/pto',
  path: '/pto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimeEntriesRoute =
  AuthenticatedTimeEntriesRouteImport.update({
    id: '/time-entries',
    path: '/time-entries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiCronPurgePhotosRoute = ApiCronPurgePhotosRouteImport.update({
  id: '/api/cron/purge-photos',
  path: '/api/cron/purge-photos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKioskBootstrapRoute = ApiPublicKioskBootstrapRouteImport.update({
  id: '/api/public/kiosk/bootstrap',
  path: '/api/public/kiosk/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKioskPunchRoute = ApiPublicKioskPunchRouteImport.update({
  id: '/api/public/kiosk/punch',
  path: '/api/public/kiosk/punch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKioskStatusRoute = ApiPublicKioskStatusRouteImport.update({
  id: '/api/public/kiosk/status',
  path: '/api/public/kiosk/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKioskVerifyPinRoute = ApiPublicKioskVerifyPinRouteImport.update({
  id: '/api/public/kiosk/verify-pin',
  path: '/api/public/kiosk/verify-pin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/adjustments': typeof AdjustmentsRoute
  '/auth': typeof AuthRoute
  '/kiosk': typeof KioskRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/pto': typeof AuthenticatedPtoRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/time-entries': typeof AuthenticatedTimeEntriesRoute
  '/api/cron/purge-photos': typeof ApiCronPurgePhotosRoute
  '/api/public/kiosk/bootstrap': typeof ApiPublicKioskBootstrapRoute
  '/api/public/kiosk/punch': typeof ApiPublicKioskPunchRoute
  '/api/public/kiosk/status': typeof ApiPublicKioskStatusRoute
  '/api/public/kiosk/verify-pin': typeof ApiPublicKioskVerifyPinRoute
}
export interface FileRoutesByTo {
  '/adjustments': typeof AdjustmentsRoute
  '/auth': typeof AuthRoute
  '/kiosk': typeof KioskRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/pto': typeof AuthenticatedPtoRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/time-entries': typeof AuthenticatedTimeEntriesRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/cron/purge-photos': typeof ApiCronPurgePhotosRoute
  '/api/public/kiosk/bootstrap': typeof ApiPublicKioskBootstrapRoute
  '/api/public/kiosk/punch': typeof ApiPublicKioskPunchRoute
  '/api/public/kiosk/status': typeof ApiPublicKioskStatusRoute
  '/api/public/kiosk/verify-pin': typeof ApiPublicKioskVerifyPinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/adjustments': typeof AdjustmentsRoute
  '/auth': typeof AuthRoute
  '/kiosk': typeof KioskRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRoute
  '/_authenticated/operations': typeof AuthenticatedOperationsRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/_authenticated/pto': typeof AuthenticatedPtoRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/time-entries': typeof AuthenticatedTimeEntriesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/cron/purge-photos': typeof ApiCronPurgePhotosRoute
  '/api/public/kiosk/bootstrap': typeof ApiPublicKioskBootstrapRoute
  '/api/public/kiosk/punch': typeof ApiPublicKioskPunchRoute
  '/api/public/kiosk/status': typeof ApiPublicKioskStatusRoute
  '/api/public/kiosk/verify-pin': typeof ApiPublicKioskVerifyPinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adjustments'
    | '/auth'
    | '/kiosk'
    | '/admin'
    | '/assignments'
    | '/operations'
    | '/payroll'
    | '/pto'
    | '/reports'
    | '/time-entries'
    | '/api/cron/purge-photos'
    | '/api/public/kiosk/bootstrap'
    | '/api/public/kiosk/punch'
    | '/api/public/kiosk/status'
    | '/api/public/kiosk/verify-pin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/adjustments'
    | '/auth'
    | '/kiosk'
    | '/admin'
    | '/assignments'
    | '/operations'
    | '/payroll'
    | '/pto'
    | '/reports'
    | '/time-entries'
    | '/'
    | '/api/cron/purge-photos'
    | '/api/public/kiosk/bootstrap'
    | '/api/public/kiosk/punch'
    | '/api/public/kiosk/status'
    | '/api/public/kiosk/verify-pin'
  id:
    | '__root__'
    | '/_authenticated'
    | '/adjustments'
    | '/auth'
    | '/kiosk'
    | '/_authenticated/admin'
    | '/_authenticated/assignments'
    | '/_authenticated/operations'
    | '/_authenticated/payroll'
    | '/_authenticated/pto'
    | '/_authenticated/reports'
    | '/_authenticated/time-entries'
    | '/_authenticated/'
    | '/api/cron/purge-photos'
    | '/api/public/kiosk/bootstrap'
    | '/api/public/kiosk/punch'
    | '/api/public/kiosk/status'
    | '/api/public/kiosk/verify-pin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdjustmentsRoute: typeof AdjustmentsRoute
  AuthRoute: typeof AuthRoute
  KioskRoute: typeof KioskRoute
  ApiCronPurgePhotosRoute: typeof ApiCronPurgePhotosRoute
  ApiPublicKioskBootstrapRoute: typeof ApiPublicKioskBootstrapRoute
  ApiPublicKioskPunchRoute: typeof ApiPublicKioskPunchRoute
  ApiPublicKioskStatusRoute: typeof ApiPublicKioskStatusRoute
  ApiPublicKioskVerifyPinRoute: typeof ApiPublicKioskVerifyPinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adjustments': {
      id: '/adjustments'
      path: '/adjustments'
      fullPath: '/adjustments'
      preLoaderRoute: typeof AdjustmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations': {
      id: '/_authenticated/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthenticatedOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pto': {
      id: '/_authenticated/pto'
      path: '/pto'
      fullPath: '/pto'
      preLoaderRoute: typeof AuthenticatedPtoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/time-entries': {
      id: '/_authenticated/time-entries'
      path: '/time-entries'
      fullPath: '/time-entries'
      preLoaderRoute: typeof AuthenticatedTimeEntriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/cron/purge-photos': {
      id: '/api/cron/purge-photos'
      path: '/api/cron/purge-photos'
      fullPath: '/api/cron/purge-photos'
      preLoaderRoute: typeof ApiCronPurgePhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kiosk/bootstrap': {
      id: '/api/public/kiosk/bootstrap'
      path: '/api/public/kiosk/bootstrap'
      fullPath: '/api/public/kiosk/bootstrap'
      preLoaderRoute: typeof ApiPublicKioskBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kiosk/punch': {
      id: '/api/public/kiosk/punch'
      path: '/api/public/kiosk/punch'
      fullPath: '/api/public/kiosk/punch'
      preLoaderRoute: typeof ApiPublicKioskPunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kiosk/status': {
      id: '/api/public/kiosk/status'
      path: '/api/public/kiosk/status'
      fullPath: '/api/public/kiosk/status'
      preLoaderRoute: typeof ApiPublicKioskStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kiosk/verify-pin': {
      id: '/api/public/kiosk/verify-pin'
      path: '/api/public/kiosk/verify-pin'
      fullPath: '/api/public/kiosk/verify-pin'
      preLoaderRoute: typeof ApiPublicKioskVerifyPinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRoute
  AuthenticatedOperationsRoute: typeof AuthenticatedOperationsRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
  AuthenticatedPtoRoute: typeof AuthenticatedPtoRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedTimeEntriesRoute: typeof AuthenticatedTimeEntriesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRoute,
  AuthenticatedOperationsRoute: AuthenticatedOperationsRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
  AuthenticatedPtoRoute: AuthenticatedPtoRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedTimeEntriesRoute: AuthenticatedTimeEntriesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdjustmentsRoute: AdjustmentsRoute,
  AuthRoute: AuthRoute,
  KioskRoute: KioskRoute,
  ApiCronPurgePhotosRoute: ApiCronPurgePhotosRoute,
  ApiPublicKioskBootstrapRoute: ApiPublicKioskBootstrapRoute,
  ApiPublicKioskPunchRoute: ApiPublicKioskPunchRoute,
  ApiPublicKioskStatusRoute: ApiPublicKioskStatusRoute,
  ApiPublicKioskVerifyPinRoute: ApiPublicKioskVerifyPinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
