/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdjustmentsRouteImport } from './routes/adjustments'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as PtoRouteImport } from './routes/pto'
import { Route as TimeEntriesRouteImport } from './routes/time-entries'
import { Route as ApiPublicKioskBootstrapRouteImport } from './routes/api/public/kiosk/bootstrap'
import { Route as ApiPublicKioskPunchRouteImport } from './routes/api/public/kiosk/punch'
import { Route as ApiPublicKioskStatusRouteImport } from './routes/api/public/kiosk/status'
import { Route as ApiPublicKioskVerifyPinRouteImport } from './routes/api/public/kiosk/verify-pin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdjustmentsRoute = AdjustmentsRouteImport.update({
  id: '/adjustments',
  path: '/adjustments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PtoRoute = PtoRouteImport.update({
  id: '/pto',
  path: '/pto',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeEntriesRoute = TimeEntriesRouteImport.update({
  id: '/time-entries',
  path: '/time-entries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKioskBootstrapRoute = ApiPublicKioskBootstrapRouteImport.update({
  id: '/api/public/kiosk/bootstrap',
  path: '/api/public/kiosk/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKioskPunchRoute = ApiPublicKioskPunchRouteImport.update({
  id: '/api/public/kiosk/punch',
  path: '/api/public/kiosk/punch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKioskStatusRoute = ApiPublicKioskStatusRouteImport.update({
  id: '/api/public/kiosk/status',
  path: '/api/public/kiosk/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKioskVerifyPinRoute = ApiPublicKioskVerifyPinRouteImport.update({
  id: '/api/public/kiosk/verify-pin',
  path: '/api/public/kiosk/verify-pin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adjustments': typeof AdjustmentsRoute
  '/admin': typeof AdminRoute
  '/assignments': typeof AssignmentsRoute
  '/kiosk': typeof KioskRoute
  '/operations': typeof OperationsRoute
  '/payroll': typeof PayrollRoute
  '/pto': typeof PtoRoute
  '/time-entries': typeof TimeEntriesRoute
  '/api/public/kiosk/bootstrap': typeof ApiPublicKioskBootstrapRoute
  '/api/public/kiosk/punch': typeof ApiPublicKioskPunchRoute
  '/api/public/kiosk/status': typeof ApiPublicKioskStatusRoute
  '/api/public/kiosk/verify-pin': typeof ApiPublicKioskVerifyPinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adjustments': typeof AdjustmentsRoute
  '/admin': typeof AdminRoute
  '/assignments': typeof AssignmentsRoute
  '/kiosk': typeof KioskRoute
  '/operations': typeof OperationsRoute
  '/payroll': typeof PayrollRoute
  '/pto': typeof PtoRoute
  '/time-entries': typeof TimeEntriesRoute
  '/api/public/kiosk/bootstrap': typeof ApiPublicKioskBootstrapRoute
  '/api/public/kiosk/punch': typeof ApiPublicKioskPunchRoute
  '/api/public/kiosk/status': typeof ApiPublicKioskStatusRoute
  '/api/public/kiosk/verify-pin': typeof ApiPublicKioskVerifyPinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adjustments': typeof AdjustmentsRoute
  '/admin': typeof AdminRoute
  '/assignments': typeof AssignmentsRoute
  '/kiosk': typeof KioskRoute
  '/operations': typeof OperationsRoute
  '/payroll': typeof PayrollRoute
  '/pto': typeof PtoRoute
  '/time-entries': typeof TimeEntriesRoute
  '/api/public/kiosk/bootstrap': typeof ApiPublicKioskBootstrapRoute
  '/api/public/kiosk/punch': typeof ApiPublicKioskPunchRoute
  '/api/public/kiosk/status': typeof ApiPublicKioskStatusRoute
  '/api/public/kiosk/verify-pin': typeof ApiPublicKioskVerifyPinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adjustments'
    | '/admin'
    | '/assignments'
    | '/kiosk'
    | '/operations'
    | '/payroll'
    | '/pto'
    | '/time-entries'
    | '/api/public/kiosk/bootstrap'
    | '/api/public/kiosk/punch'
    | '/api/public/kiosk/status'
    | '/api/public/kiosk/verify-pin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adjustments'
    | '/admin'
    | '/assignments'
    | '/kiosk'
    | '/operations'
    | '/payroll'
    | '/pto'
    | '/time-entries'
    | '/api/public/kiosk/bootstrap'
    | '/api/public/kiosk/punch'
    | '/api/public/kiosk/status'
    | '/api/public/kiosk/verify-pin'
  id:
    | '__root__'
    | '/'
    | '/adjustments'
    | '/admin'
    | '/assignments'
    | '/kiosk'
    | '/operations'
    | '/payroll'
    | '/pto'
    | '/time-entries'
    | '/api/public/kiosk/bootstrap'
    | '/api/public/kiosk/punch'
    | '/api/public/kiosk/status'
    | '/api/public/kiosk/verify-pin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdjustmentsRoute: typeof AdjustmentsRoute
  AdminRoute: typeof AdminRoute
  AssignmentsRoute: typeof AssignmentsRoute
  KioskRoute: typeof KioskRoute
  OperationsRoute: typeof OperationsRoute
  PayrollRoute: typeof PayrollRoute
  PtoRoute: typeof PtoRoute
  TimeEntriesRoute: typeof TimeEntriesRoute
  ApiPublicKioskBootstrapRoute: typeof ApiPublicKioskBootstrapRoute
  ApiPublicKioskPunchRoute: typeof ApiPublicKioskPunchRoute
  ApiPublicKioskStatusRoute: typeof ApiPublicKioskStatusRoute
  ApiPublicKioskVerifyPinRoute: typeof ApiPublicKioskVerifyPinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adjustments': {
      id: '/adjustments'
      path: '/adjustments'
      fullPath: '/adjustments'
      preLoaderRoute: typeof AdjustmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pto': {
      id: '/pto'
      path: '/pto'
      fullPath: '/pto'
      preLoaderRoute: typeof PtoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-entries': {
      id: '/time-entries'
      path: '/time-entries'
      fullPath: '/time-entries'
      preLoaderRoute: typeof TimeEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kiosk/bootstrap': {
      id: '/api/public/kiosk/bootstrap'
      path: '/api/public/kiosk/bootstrap'
      fullPath: '/api/public/kiosk/bootstrap'
      preLoaderRoute: typeof ApiPublicKioskBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kiosk/punch': {
      id: '/api/public/kiosk/punch'
      path: '/api/public/kiosk/punch'
      fullPath: '/api/public/kiosk/punch'
      preLoaderRoute: typeof ApiPublicKioskPunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kiosk/status': {
      id: '/api/public/kiosk/status'
      path: '/api/public/kiosk/status'
      fullPath: '/api/public/kiosk/status'
      preLoaderRoute: typeof ApiPublicKioskStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kiosk/verify-pin': {
      id: '/api/public/kiosk/verify-pin'
      path: '/api/public/kiosk/verify-pin'
      fullPath: '/api/public/kiosk/verify-pin'
      preLoaderRoute: typeof ApiPublicKioskVerifyPinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdjustmentsRoute: AdjustmentsRoute,
  AdminRoute: AdminRoute,
  AssignmentsRoute: AssignmentsRoute,
  KioskRoute: KioskRoute,
  OperationsRoute: OperationsRoute,
  PayrollRoute: PayrollRoute,
  PtoRoute: PtoRoute,
  TimeEntriesRoute: TimeEntriesRoute,
  ApiPublicKioskBootstrapRoute: ApiPublicKioskBootstrapRoute,
  ApiPublicKioskPunchRoute: ApiPublicKioskPunchRoute,
  ApiPublicKioskStatusRoute: ApiPublicKioskStatusRoute,
  ApiPublicKioskVerifyPinRoute: ApiPublicKioskVerifyPinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
